### ISSUE TITLE
Unable to compile signatures with Java 9

### ISSUE THREAD

**Issue by liujed** [apl-cornell/jif#3]
The Jif signatures for Java system classes cannot be built with Java 9, thanks to the awesomeness that is Jigsaw. Unknown whether there is an easy workaround. Ideally, we'd be able to convince javac that we really do know what we are doing, and have it compile these classes anyway, but this doesn't appear possible. Hopefully, the Jif signatures mechanism won't have to be redesigned to fix this issue...

```
jif-sig:
    [apply] jifc: sig-classes/java/lang/Throwable.java:1: error: package exists in another module: java.base
    [apply]     package java.lang;
    [apply]     ^
    [apply]     sig-classes/java/lang/NullPointerException.java:1: error: package exists in another module: java.base
```

**Comment by liujed** [comment]
This looks relevant (and perhaps promising): https://stackoverflow.com/questions/36270671/how-to-patch-openjdk-9-with-jigsaw-integrated

**Comment by tmagrino** [comment]
Does this also affect [polyglot](https://github.com/polyglot-compiler/polyglot) or is this specific to Jif?

**Comment by liujed** [comment]
It's also a Polyglot issue (in the sense that Polyglot's `javac` backend can no longer compile classes declared to be in `java.lang`, for instance), but Jif's build is broken as a result.

**Comment by andrewcmyers** [comment]
fixed using --patch-module option.
