### ISSUE TITLE
Does JIF support Java 8 features?

### ISSUE THREAD

**Issue by uraj** [apl-cornell/jif#6]
For example, lambda expressions. I tried JIF 3.5.0 a little bit and it seems that JIF does not recognize the lambda expression syntax, but maybe I did something wrong. Could someone clarify that?

**Comment by andrewcmyers** [comment]
No, Jif does not support lambda expressions yet. Its Java support is roughly at the level of Java 1.4. It does have a form of generics but only for label and principal parameters, not type parameters. There is a branch that also supports type parameters.

**Comment by uraj** [comment]
Thanks!
